---
- name: Modif port
  hosts: web

  tasks:

    - name: Add Listen 8080 to ports.conf
      lineinfile:
        path: /etc/apache2/ports.conf
        line: 'Listen 8080'
      notify: restart-apache

  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted