---
- name: Installer Apache2
  hosts: all
  become: true
  
  tasks:
    - name: Installer Apache2 sur les systèmes Debian
      apt:
        name: apache2
        state: latest
      when: ansible_os_family == 'Debian'
  
    - name: Installer Apache2 sur les systèmes CentOS
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == 'RedHat'
