---
- hosts: webserver
  become: yes
  vars_files:
    - vars/defaults.yml

  tasks:
    - name: Installer les paquets necessaires
      package:
        name:
          - apache2
          - "php{{ php_version }}"
          - "php{{ php_version }}-mysql"
          - libapache2-mod-php
        state: present

    - name: Activer le module mod_rewrite
      module:
        name: rewrite
        state: present

    - name: Copier la configuration du VirtualHost
      template:
        src: template/apache_vhost.j2
        dest: /etc/apache2/sites-enabled/000-default.conf
      notify: restart-apache

    - name: Copier le fichier PHP de connexion à la base de données
      template:
        src: template/testconnexion.php.j2
        dest: /home/user1/webpage/index.php

- hosts: database
  become: yes
  vars_files:
    - vars/defaults.yml

  tasks:
    - name: Installer les paquets necessaires
      package:
        name:
          - mysql-server
          - mysql-client
          - python3-mysqldb
          - libmysqlclient-dev
        state: present

    - name: Start et enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Creer la base de données MySQL
      mysql_db:
        name: "{{ mysql_db }}"
        state: present

    - name: Creer l'utilisateur MySQL
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        host: '%'
        state: present

    - name: Permettre de se connecter a distance
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
         - restart-mysql

  handlers:

    - name: restart-apache
      systemd:
        name: apache2
        state: restarted
        daemon_reload: yes

    - name: restart-mysql
      service:
        name: mysql
        state: restarted